name: Daily Stock Bot

on:
  schedule:
    - cron: '0 7 * * *'  # varje dag kl 07 UTC (~09 svensk tid)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install yfinance numpy pandas feedparser textblob requests beautifulsoup4

      - name: Run bot
        run: python main.py
